#!/usr/bin/env sh
# /git-config-filters
# Configures the diff function for PowerPoint files to decompress
# before comparison.
#
# By        : Leomar Durán <https://github.com/lduran2/>
# When      : 2021-12-13t19:03
# Where     : Temple University
# For       : CIS 114
# Version   : 1.0.0
# Canonical : https://github.com/lduran2/cis4526-machine_learning_foundations/blob/master/git-config-filters
#
# CHANGELOG :
#    v1.0.0 - 2021-12-13t19:03
#        set to unzip on diff
git config diff.zip.textconv 'unzip -c -a'